#!/usr/bin/env python3
from datetime import datetime, timezone
import email
import imaplib
import json
import re
import shutil
import smtplib
import sys
import time
from email.message import EmailMessage
from email.utils import parseaddr
from zoneinfo import ZoneInfo

from common import (
    PENDING,
    APPROVED,
    REJECTED,
    global_env,
    cfg_int,
    approval_hash,
    verify_totp,
    atomic_write_json,
    generate_run_password,
    run_password_hash,
)

APPROVE_RE = re.compile(
    r"^\s*APPROVE\s+([A-Za-z0-9_.-]+)\s+([a-fA-F0-9]{64})\s+([0-9]{6})\s*$",
    re.MULTILINE,
)

REJECT_RE = re.compile(
    r"^\s*REJECT\s+([A-Za-z0-9_.-]+)\s+([a-fA-F0-9]{64})\s*$",
    re.MULTILINE,
)

def log(msg):
    print(f"[privilege-check] {msg}", flush=True)

def get_body(msg):
    if msg.is_multipart():
        parts = []
        for part in msg.walk():
            if part.get_content_type() == "text/plain":
                payload = part.get_payload(decode=True)
                if payload:
                    charset = part.get_content_charset() or "utf-8"
                    parts.append(payload.decode(charset, errors="replace"))
        return "\n".join(parts)

    payload = msg.get_payload(decode=True)
    if not payload:
        return ""

    charset = msg.get_content_charset() or "utf-8"
    return payload.decode(charset, errors="replace")

def send_system_email(to_addr, subject, body):
    g = global_env()

    smtp_host = g.get("SMTP_HOST", "smtp.gmail.com")
    smtp_port = int(g.get("SMTP_PORT", "587"))

    smtp_from = g["WORKFLOW_EMAIL_ADDRESS"]
    smtp_user = g["WORKFLOW_EMAIL_USER"]
    smtp_password = g["WORKFLOW_EMAIL_APP_PASSWORD"]

    msg = EmailMessage()
    msg["From"] = smtp_from
    msg["To"] = to_addr
    msg["Reply-To"] = smtp_from
    msg["Subject"] = subject
    msg.set_content(body)

    with smtplib.SMTP(smtp_host, smtp_port, timeout=30) as s:
        s.starttls()
        s.login(smtp_user, smtp_password)
        s.send_message(msg)

def move_request(path, target_dir, suffix=None):
    manifest = json.loads(path.read_text(encoding="utf-8"))
    rid = manifest["approval"]["request_id"]

    if suffix:
        target = target_dir / f"{rid}.{suffix}.json"
    else:
        target = target_dir / f"{rid}.json"

    if target.exists():
        target = target_dir / f"{rid}.{suffix or 'moved'}.{int(time.time())}.json"

    shutil.move(str(path), str(target))
    return target

def reject_request(path, reason):
    manifest = json.loads(path.read_text(encoding="utf-8"))
    manifest["state"]["status"] = "rejected"
    manifest["state"]["reason"] = reason
    manifest["state"]["rejected_at_epoch"] = int(time.time())
    atomic_write_json(path, manifest)
    target = move_request(path, REJECTED, reason)
    log(f"rejected {manifest['approval']['request_id']}: {reason}")
    return target

def approve_request(path):
    g = global_env()

    manifest = json.loads(path.read_text(encoding="utf-8"))
    rid = manifest["approval"]["request_id"]
    requester = manifest["approval"]["requester"]
    notify_to = manifest["approval"]["requester_notify_to"]
    digest = approval_hash(manifest)

    run_password_bytes = cfg_int(g, "RUN_PASSWORD_BYTES", 24)
    run_timeout = cfg_int(g, "RUN_AFTER_APPROVAL_TIMEOUT_SEC", 3600)

    run_password = generate_run_password(run_password_bytes)
    salt = generate_run_password(16)

    tz = g.get("TZ", "UTC")
    try:
        ZoneInfo(tz)
    except Exception:
        tz = "UTC"

    now = int(time.time())
    run_expires_at = now + run_timeout

    manifest["state"]["status"] = "approved"
    manifest["state"]["approved_at_epoch"] = now
    manifest["state"]["run_password_salt"] = salt
    manifest["state"]["run_password_hash"] = run_password_hash(run_password, salt)
    manifest["state"]["run_password_expires_at_epoch"] = run_expires_at
    manifest["state"]["failed_run_password_attempts"] = 0
    manifest["state"]["max_run_password_attempts"] = cfg_int(g, "RUN_PASSWORD_MAX_ATTEMPTS", 5)

    atomic_write_json(path, manifest)

    try:
        send_system_email(
            notify_to,
            f"[privilege approval] approved request {rid}",
            f"""Your privileged command request was approved.

Request ID:
{rid}

SHA256 digest:
{digest}

Your one-time run password:
{run_password}

Run the approved commands with:

run-approved {rid} {digest} {run_password}

Execution deadline:
{datetime.fromtimestamp(run_expires_at, timezone.utc).astimezone(ZoneInfo(tz)).strftime("%Y-%m-%d %H:%M:%S %Z")}

Important:
- This run password is generated by the system.
- It is valid only for this request.
- It can be used only once.
- It expires after the configured execution window.
"""
        )
    except Exception as e:
        manifest["state"]["status"] = "rejected"
        manifest["state"]["reason"] = "failed-to-send-run-password"
        manifest["state"]["error"] = str(e)
        manifest["state"]["rejected_at_epoch"] = int(time.time())
        atomic_write_json(path, manifest)
        target = move_request(path, REJECTED, "failed-to-send-run-password")
        log(f"rejected {rid}: failed to send run password: {e}")
        return target

    target = move_request(path, APPROVED, None)
    log(f"approved {rid} for requester {requester}; run password sent to {notify_to}")
    return target

def expire_old_pending():
    now = int(time.time())

    for path in list(PENDING.glob("*.json")):
        try:
            manifest = json.loads(path.read_text(encoding="utf-8"))
            expires_at = int(manifest["approval"].get("expires_at_epoch", 0))
            if not expires_at or now > expires_at:
                reject_request(path, "expired-before-admin-approval")
        except Exception as e:
            log(f"failed to expire-check pending {path}: {e}")

def expire_old_approved():
    now = int(time.time())

    for path in list(APPROVED.glob("*.json")):
        try:
            manifest = json.loads(path.read_text(encoding="utf-8"))
            expires_at = int(manifest["state"].get("run_password_expires_at_epoch", 0))
            if not expires_at or now > expires_at:
                manifest["state"]["status"] = "rejected"
                manifest["state"]["reason"] = "expired-after-approval"
                manifest["state"]["rejected_at_epoch"] = now
                atomic_write_json(path, manifest)
                move_request(path, REJECTED, "expired-after-approval")
                log(f"approved request expired before execution: {manifest['approval']['request_id']}")
        except Exception as e:
            log(f"failed to expire-check approved {path}: {e}")

def find_pending(rid):
    path = PENDING / f"{rid}.json"
    return path if path.exists() else None

def process_workflow_mailbox():
    g = global_env()

    approver = g["APPROVER_EMAIL"].lower()

    imap_host = g.get("IMAP_HOST", "imap.gmail.com")
    imap_port = int(g.get("IMAP_PORT", "993"))
    imap_user = g["WORKFLOW_EMAIL_USER"]
    imap_password = g["WORKFLOW_EMAIL_APP_PASSWORD"]

    processed = 0

    M = imaplib.IMAP4_SSL(imap_host, imap_port)
    M.login(imap_user, imap_password)
    M.select("INBOX")

    status, data = M.search(None, "UNSEEN")
    if status != "OK":
        M.logout()
        return 0

    for num in data[0].split():
        status, msg_data = M.fetch(num, "(RFC822)")
        if status != "OK":
            continue

        msg = email.message_from_bytes(msg_data[0][1])
        sender = parseaddr(msg.get("From", ""))[1].lower()
        body = get_body(msg)

        if sender != approver:
            continue

        approve_match = APPROVE_RE.search(body)
        reject_match = REJECT_RE.search(body)

        if not approve_match and not reject_match:
            continue

        if approve_match:
            rid, claimed_digest, admin_otp = approve_match.groups()
            path = find_pending(rid)

            if not path:
                M.store(num, "+FLAGS", "\\Seen")
                continue

            manifest = json.loads(path.read_text(encoding="utf-8"))
            actual_digest = approval_hash(manifest)

            if claimed_digest.lower() != actual_digest.lower():
                reject_request(path, "approval-hash-mismatch")
                M.store(num, "+FLAGS", "\\Seen")
                processed += 1
                continue

            now = int(time.time())
            request_expires_at = int(manifest["approval"]["expires_at_epoch"])
            if now > request_expires_at:
                reject_request(path, "expired-before-admin-approval")
                M.store(num, "+FLAGS", "\\Seen")
                processed += 1
                continue

            past_sec = cfg_int(g, "TOTP_ACCEPT_PAST_SEC", 240)
            future_sec = cfg_int(g, "TOTP_ACCEPT_FUTURE_SEC", 30)

            if not verify_totp(admin_otp, past_sec=past_sec, future_sec=future_sec):
                reject_request(path, "bad-admin-otp")
                M.store(num, "+FLAGS", "\\Seen")
                processed += 1
                continue

            approve_request(path)
            M.store(num, "+FLAGS", "\\Seen")
            processed += 1
            continue

        if reject_match:
            rid, claimed_digest = reject_match.groups()
            path = find_pending(rid)

            if not path:
                M.store(num, "+FLAGS", "\\Seen")
                continue

            manifest = json.loads(path.read_text(encoding="utf-8"))
            actual_digest = approval_hash(manifest)

            if claimed_digest.lower() != actual_digest.lower():
                reject_request(path, "reject-hash-mismatch")
            else:
                reject_request(path, "admin-rejected")

            M.store(num, "+FLAGS", "\\Seen")
            processed += 1

    M.logout()
    return processed

def pending_or_approved_exists():
    return any(PENDING.glob("*.json")) or any(APPROVED.glob("*.json"))

def main():
    loop = "--loop" in sys.argv
    g = global_env()
    poll_interval = cfg_int(g, "POLL_INTERVAL_SEC", 60)

    while True:
        expire_old_pending()
        expire_old_approved()

        if any(PENDING.glob("*.json")):
            try:
                process_workflow_mailbox()
            except Exception as e:
                log(f"workflow mailbox check failed: {e}")

        expire_old_pending()
        expire_old_approved()

        if not pending_or_approved_exists():
            log("no pending or approved requests; exiting")
            return 0

        if not loop:
            return 0

        log(f"pending or approved requests remain; sleeping {poll_interval} seconds")
        time.sleep(poll_interval)

if __name__ == "__main__":
    raise SystemExit(main())